name: Go Tests
on:
  push:
    branches:
    - main
    paths:
    - 'go.mod'
    - 'go.sum'
    - '*.go'
    - '.github/workflows/go-tests.yaml'
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'go.mod'
    - 'go.sum'
    - '*.go'
    - '.github/workflows/go-tests.yaml'

concurrency:
  group: go-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    - name: Get dependencies
      run: go mod tidy
    - name: Build
      run: go build ./...
    - name: Run tests
      run: go test ./...
